apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ICB7CiAgICAgImF1dGhzIjogewogICAgICAgImdoY3IuaW8iOiB7CiAgICAgICAgICJhdXRoIjogImVXRnpjR2xqYUdsb2FXNDZaMmh3WDBWUmJGSlRXRGgwWXpkS1UwbDJla2hrWjA1d2RrNTZhV05JT1dKVGNqTnVZVUZEUnc9PSIKICAgICAgIH0KICAgICB9CiAgIH0K
type: kubernetes.io/dockerconfigjson
